name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install dependencies
        run: npm ci # the same as npm install but it is suitable for ci

      - name: Check format
        run: npm run format:check

      - name: Automation test
        run: npm test -- --coverage
        env:
          CI: true

      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build

      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain uninterested-us-staging.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
